### ISSUE TITLE
Datatype Error for create_empty_netcdf

### ISSUE THREAD

**Issue by biwabel** [cchwala/radolan_to_netcdf#15]
When following the [example_download_and_parse_radklim-yw_data.ipynb](https://github.com/cchwala/radolan_to_netcdf/blob/master/notebooks/example_download_and_parse_radklim-yw_data.ipynb) notebook, an error occurs when executing code cell 3:
`rtn.create_empty_netcdf(fn=fn_netcdf, product_name='YW')`

The new empty nc array is trying to be filled with fill_value = -9999. However, the datatype is defined as i1 in three places in radolan_to_netcdf/radolan_product_netcdf_config.py, which leads to an overflow error with python. -9999 at least is i2.

I suggest replacing all i1 values within radolan_product_netcdf_config.py with i2, at least this made the notebook run through smoothly. Didn't check dependencies and other aspects though.

Hope this helps.

**Comment by cchwala** [comment]
closed via #16
